# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "booboobanisher-infrastructure-terraform-state-bucket"
    dynamodb_table = "booboobanisher-infrastructure-terraform-locks-table"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "eu-west-1"
  }
}
