name: Zip and Flyway

on:
  push:
    branches:
      - main 

env:
  AWS_REGION: "eu-west-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
  id-token: write
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bbb
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' 
    
    - name: Build and Publish
      run: |
        dotnet build --configuration Release
        dotnet publish --configuration Release -o ./publish
        zip -r booboobanisher.zip ./publish 
  
  Flyway:
    name: Run Flyway Migration
    needs: compile
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3.0.0
    - name: Continuous Integration Flyway Clean Migrate
      run: >-
        docker run --rm
        --volume ${{ github.workspace }}/migrations:/flyway/sql:ro
        redgate/flyway
        -url="jdbc:postgresql://booboobanisher-db.cidtxn2ndtwc.eu-west-1.rds.amazonaws.com:5432/bbbdb"
        -user="dbadmin"
        -password=${{ secrets.DB_PASSWORD }} migrate